### ISSUE TITLE
[Errno 2] No such file or directory: 'DeepNet/models/imagenet.npy'

### ISSUE THREAD

**Issue by MKSwaminathan** [aqeelanwar/DRLwithTL_real#12]
Hello,

I am getting the following error when I run main_code.py: 
FileNotFoundError: [Errno 2] No such file or directory: 'DeepNet/models/imagenet.npy'
which seems to be referenced in DeepNet/network/network.py as well as DeepNet/network/agent.py. Maybe I am missing something, but imagenet.npy does not seem to be generated anywhere, and *.npy files are in the .gitignore, so I don't believe something went wrong when I cloned. 
Please let me know the fix and if there is anything I may be missing. Thank you!

Here are my specs as well as the full error:
macOS 10.13.6 High Sierra

--------------------- Config File ---------------------
run_name:                      Tello_indoor
custom_load:                   False
custom_load_path:              DeepNet/models/e2e/e2e
env_type:                      VanLeer
load_data:                     False
load_data_path:                DeepNet/models/Tello_indoor/VanLeer/
num_actions:                   3
train_type:                    meta
wait_before_train:             9
max_iters:                     8000
buffer_len:                    2400
batch_size:                    8
epsilon_saturation:            2000
crash_thresh:                  1.3
gamma:                         0.99
dropout_rate:                  0.1
lr:                            0.1
Q_clip:                        True
train_interval:                200
update_target_interval:        400
Data tuple loaded:  0
--------------------- Loading DeepAgent ---------------------
Traceback (most recent call last):
  File "main_code.py", line 56, in <module>
    tensorboard_path = cfg.load_data_path)
  File "my-path-to-repo/DRLwithTL_real/DeepNet/network/agent.py", line 516, in __init__
    self.model = AlexNetDuel(self.X, num_actions, train_fc)
  File "my-path-to-repo/DRLwithTL_real/DeepNet/network/network.py", line 11, in __init__
    weights = np.load(open(weights_path, "rb"), encoding="latin1").item()
FileNotFoundError: [Errno 2] No such file or directory: 'DeepNet/models/imagenet.npy'

**Comment by aqeelanwar** [comment]
Hello,

You can download the required file from the link below
https://gtvault-my.sharepoint.com/:u:/g/personal/manwar8_gatech_edu/Ef52J48ugL1CnrWmrUVj0JgBOd1-PIiPU2ZUcQ5mqnP0tA?e=QD53S0

and place it in DeepNet/models

**Comment by edsun123** [comment]
Hi, I also came across the same issue. I assumed that we have to place the imagenet files but the link is already expired.
Is there another link to it?

**Comment by aqeelanwar** [comment]
Let me know if the following link works
https://gtvault-my.sharepoint.com/:u:/g/personal/manwar8_gatech_edu/Ef52J48ugL1CnrWmrUVj0JgBeaW3Bl9EubX6QPHYqf7Vnw?e=QLGjYW

**Comment by edsun123** [comment]
Thanks!

 There is an issue with deprecated operations with tensorflows but I will post that in another issue

**Comment by Pratiquea** [comment]
> Let me know if the following link works
> https://gtvault-my.sharepoint.com/:u:/g/personal/manwar8_gatech_edu/Ef52J48ugL1CnrWmrUVj0JgBeaW3Bl9EubX6QPHYqf7Vnw?e=QLGjYW

Hi, I am unable to access the link since it has expired. Can you please create the link to the model file again?

**Comment by aqeelanwar** [comment]
This link should work.
https://drive.google.com/file/d/1Ei4mCzjfLY5ql6ILIUHaCtAR2XF6BtAM
