### ISSUE TITLE
issue with aqeelanwar / DRLwithTL_real code

### ISSUE THREAD

**Issue by segun-adebayo** [aqeelanwar/DRLwithTL_real#14]
This is the entire error

(autonomous_drone) C:\Users\Bowen Research Grant\DRLwithTL_real>python main_code.py
2020-07-31 09:56:06.889772: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-07-31 09:56:06.899885: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
--------------------- Config File ---------------------
run_name:                      Tello_indoor
custom_load:                   False
custom_load_path:              DeepNet/models/e2e/e2e
env_type:                      VanLeer
load_data:                     False
load_data_path:                DeepNet/models/Tello_indoor/VanLeer/
num_actions:                   3
train_type:                    e2e
wait_before_train:             9
max_iters:                     8000
buffer_len:                    2400
batch_size:                    8
epsilon_saturation:            2000
crash_thresh:                  1.3
gamma:                         0.99
dropout_rate:                  0.1
lr:                            0.1
Q_clip:                        True
train_interval:                200
update_target_interval:        400
Data tuple loaded:  0
--------------------- Loading DeepAgent ---------------------
WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\agent.py:495: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\agent.py:503: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\Anaconda3\envs\autonomous_drone\lib\site-packages\tensorflow_core\python\ops\image_ops_impl.py:1518: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Loading imagenet weights for the conv layers and random for fc layers
WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\network.py:33: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\Anaconda3\envs\autonomous_drone\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From C:\Users\Bowen Research Grant\Anaconda3\envs\autonomous_drone\lib\site-packages\tensorflow_core\python\layers\core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\network.py:91: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\network.py:95: The name tf.nn.relu_layer is deprecated. Please use tf.compat.v1.nn.relu_layer instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\network.py:97: The name tf.nn.xw_plus_b is deprecated. Please use tf.compat.v1.nn.xw_plus_b instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\loss_functions.py:9: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\agent.py:531: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\agent.py:533: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

2020-07-31 09:57:31.200044: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-31 09:57:31.281172: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-07-31 09:57:31.289272: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-31 09:57:31.297262: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Adebayo
2020-07-31 09:57:31.300802: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Adebayo
WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\agent.py:534: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\agent.py:535: The name tf.local_variables_initializer is deprecated. Please use tf.compat.v1.local_variables_initializer instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\agent.py:536: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

--------------------- Loading DeepAgent ---------------------
Loading imagenet weights for the conv layers and random for fc layers
WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\heat_map_network.py:163: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\heat_map_network.py:127: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\heat_map_network.py:293: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\heat_map.py:20: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\heat_map.py:20: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

Traceback (most recent call last):
  File "main_code.py", line 67, in <module>
    DepthAgent = heat_map()
  File "C:\Users\Bowen Research Grant\DRLwithTL_real\DeepNet\network\heat_map.py", line 24, in __init__
    saver.restore(self.sess, model_data_path)
  File "C:\Users\Bowen Research Grant\Anaconda3\envs\autonomous_drone\lib\site-packages\tensorflow_core\python\training\saver.py", line 1280, in restore
    if not checkpoint_management.checkpoint_exists_internal(checkpoint_prefix):
  File "C:\Users\Bowen Research Grant\Anaconda3\envs\autonomous_drone\lib\site-packages\tensorflow_core\python\training\checkpoint_management.py", line 366, in checkpoint_exists_internal
    if file_io.get_matching_files(pathname):
  File "C:\Users\Bowen Research Grant\Anaconda3\envs\autonomous_drone\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 363, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\Users\Bowen Research Grant\Anaconda3\envs\autonomous_drone\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 384, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: Deepnet/models/fcrn : The system cannot find the path specified.
; No such process

**Comment by aqeelanwar** [comment]
The issue is the missing ckpt file for depth map estimation from monocular images. You need to download the required file and place it in the following location
`Deepnet/models/fcrn/NYU_FCRN.ckpt`

The required can be downloaded from the GitHub page https://github.com/iro-cp/FCRN-DepthPrediction or from the following link http://campar.in.tum.de/files/rupprecht/depthpred/NYU_FCRN-checkpoint.zip

**Comment by amitkumar47** [comment]
Hello Sir,
Both the links for ckpt files are not working.
could you pls, upload it and share the link with us.
it would be too helpful.
