### ISSUE TITLE
One of the modules is missing attribute 'pb' 

### ISSUE THREAD

**Issue by edsun123** [aqeelanwar/DRLwithTL_real#16]
I suspect this maybe related to what version of tensorflow installed: 
(tensorboard==2.0.0
tensorflow-estimator==2.0.1
tensorflow-gpu==1.15.2
tensorflow-tensorboard==0.4.0)

Traceback (most recent call last):
  File "main_code.py", line 10, in <module>
    from DeepNet.network.agent import DeepAgent
  File "/home/user/Desktop/drone/DRLwithTL_real/DeepNet/network/agent.py", line 5, in <module>
    import tensorflow as tf
  File "/home/user/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/home/user/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 36, in <module>
    from tensorflow._api.v1 import compat
  File "/home/user/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow_core/_api/v1/compat/__init__.py", line 24, in <module>
    from tensorflow._api.v1.compat import v2
  File "/home/user/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow_core/_api/v1/compat/v2/__init__.py", line 322, in <module>
    from tensorboard.summary._tf import summary
  File "/home/user/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1
  File "/home/user/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorboard/summary/v1.py", line 46, in <module>
    pr_curve_pb = _pr_curve_summary.pb
AttributeError: module 'tensorboard.plugins.pr_curve.summary' has no attribute 'pb'

**Comment by edsun123** [comment]
Had to change the requirements.txt particularly on the tensorboard versions.
